### PR TITLE
ANN additions

### PR DESCRIPTION
**Pull request by apete**

### CODE REVIEW

**Comment by apete** [comment]
@DanielMartensson I added L1 and L2 regularisation as well call "lasso" and "ridge" on the trainer to set it up.

**Comment by DanielMartensson** [comment]
> @DanielMartensson I added L1 and L2 regularisation as well call "lasso" and "ridge" on the trainer to set it up.

@apete Does OjAlgo only have Dense Layer as layer? No CNN?
CNN is the key behind computer vision with NN.

**Comment by apete** [comment]
Yes, only dense fully connected layers at this point.

**Comment by DanielMartensson** [comment]
> Yes, only dense fully connected layers at this point.

@apete 
Jag har talat med lite folk på Umeå Universitet och dom rekommenderar alltid CNN när det kommer till bildigenkänning. Det är CNN + YOLO algoritmen som har gjort neurala nätverk kraftigt i komplexa förhållanden.

Själv håller jag på med Fisherfaces, vikter innefattar SVD och Generalized Eigenvalue Problem tillsammans. Inte lika kraftfullt som CNN, men man kan ha typ minimalt med data och få en riktig bra identifiering typ 98%. 

Om du tar och kollar på jFaces som jag har byggt, så kan du se att jag har byggt in en C-kodgenerare helt i Java. Det skulle vara häftigt om ojAlgo hade också en C-kodgenererare. Jag vet dock inte vad målet med OjAlgo är, om det är att vara en applikation eller verktyg.

Bra kämpat. Jag är imponerad av OjAlgo. Mycket snabbt också. Har för mig att OjAlgo är snabbare än GNU Octave. Men en sak som GNU Octave var snabbare med är att man kunde göra flera saker samtidigt i GNU Octave tack vare vektoriseringen. Nu använder Octave OpenBLAS så det är fusk.  ;)

PS.
Du är väll den som gör bänktesterna för OjAlgo? Du skulle fått jämföra med rent C kod också. Alltså hur multiplikation i OjAlgo jämfört med multiplikation i C (ej BLAS) med minimal for-loop.

**Comment by apete** [comment]
@DanielMartensson Sounds like you're trying to inspire me to do more work...

ojAlgo is a code library – a toolbox for others to use when building higher level more complex stuff.

The stuff that I've built has primarily been on behalf of paying customers, and that's the only possible way. Major work has to be paid for somehow. Adding CNN:s seems like a major undertaking.

If you want to donate your C code generator I'll help you get it in.

There is info regarding how ojAlgo (and other libraries) compare to native code.

https://www.ojalgo.org/2018/03/matrix-multiplication-on-different-jvms/ and read the "Relative to what?" section.

Also the [Java Matrix Benchmark](https://lessthanoptimal.github.io/Java-Matrix-Benchmark/) publishes results both for pure Java implementations as well as mixed native / Java code libraries.

In all those cases some code library, C or Fortran, is used. What you suggest is comparing the languages/compilers. I feel that's beyond my scope.

**Comment by DanielMartensson** [comment]
> @DanielMartensson Sounds like you're trying to inspire me to do more work...
> 
> ojAlgo is a code library – a toolbox for others to use when building higher level more complex stuff.
> 
> The stuff that I've built has primarily been on behalf of paying customers, and that's the only possible way. Major work has to be paid for somehow. Adding CNN:s seems like a major undertaking.
> 
> If you want to donate your C code generator I'll help you get it in.
> 
> There is info regarding how ojAlgo (and other libraries) compare to native code.
> 
> https://www.ojalgo.org/2018/03/matrix-multiplication-on-different-jvms/ and read the "Relative to what?" section.
> 
> Also the [Java Matrix Benchmark](https://lessthanoptimal.github.io/Java-Matrix-Benchmark/) publishes results both for pure Java implementations as well as mixed native / Java code libraries.
> 
> In all those cases some code library, C or Fortran, is used. What you suggest is comparing the languages/compilers. I feel that's beyond my scope.

Jag inspirerar bara mina egna projekt. Jag marknadsför dom heller inte. Jag gillar bara lösa problem. Jag håller faktiskt på att bygga en C-kod generare som du kan få ta del utav. Men jag väntar på nästa version av OjAlgo när du publicerar den för Maven Repository. Då bygger jag vidare och meddelar dig att nu är den klar.

**Comment by apete** [comment]
I was hoping to get some sort of confirmation, from you, that what’s in that PR https://github.com/optimatika/ojAlgo/pull/263 works. In particular dropouts, L1 and L2 regularisation. As soon as I get that I’ll release a new version. I don’t plan to add anything more.

**Comment by DanielMartensson** [comment]
> I was hoping to get some sort of confirmation, from you, that what’s in that PR #263 works. In particular dropouts, L1 and L2 regularisation. As soon as I get that I’ll release a new version. I don’t plan to add anything more.
> […](#)
> On 7 Aug 2020, at 10:26, Daniel Mårtensson ***@***.***> wrote: @DanielMartensson Sounds like you're trying to inspire me to do more work... ojAlgo is a code library – a toolbox for others to use when building higher level more complex stuff. The stuff that I've built has primarily been on behalf of paying customers, and that's the only possible way. Major work has to be paid for somehow. Adding CNN:s seems like a major undertaking. If you want to donate your C code generator I'll help you get it in. There is info regarding how ojAlgo (and other libraries) compare to native code. https://www.ojalgo.org/2018/03/matrix-multiplication-on-different-jvms/ and read the "Relative to what?" section. Also the Java Matrix Benchmark publishes results both for pure Java implementations as well as mixed native / Java code libraries. In all those cases some code library, C or Fortran, is used. What you suggest is comparing the languages/compilers. I feel that's beyond my scope. Jag inspirerar bara mina egna projekt. Jag marknadsför dom heller inte. Jag gillar bara lösa problem. Jag håller faktiskt på att bygga en C-kod generare som du kan få ta del utav. Men jag väntar på nästa version av OjAlgo när du publicerar den för Maven Repository. Då bygger jag vidare och meddelar dig att nu är den klar. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Was hoping? Jag skriver här när jag är klar? Går det bra?

Jag använder endast GitHub som ett moln. Vet ej hur man egentligen använder github i projektform med flera personer involverad. 

Okej, bra. Jag gillar inte ändringar. Har kört Deeplearning4J förut och för varje versionsuppdatering så är det massvis med ändringar hur man använder deeplearning4j.

**Comment by apete** [comment]
Yes, leaving comments here is fine.

The number of necessary changes is something you can give feedback on. The one thing you have to do is a search-and-replace "NetworkBuilder" -> "NetworkTrainer". There's no way around that. (The old NetworkBuilder has been split into a NetworkBuilder and a NetworkTrainer, and most of what you accessed before is now in the NetworkTrainer.) Most/all other things should work as before even if they're marked as deprecated. To get the best performance, and avoid future problems, you should also get rid of any use of deprecated methods, but short term it's not necessary.

**Pull request merged**
