### PR TITLE
Issue #75 - A parameterised test example

### PR DESCRIPTION
**Pull request by alf239**
Just a simple example of a parameterised test in JUnit 5. New dependency, and a good potential to drop some of the boilerplate.

### CODE REVIEW

**Comment by alf239** [comment]
Eclipse runner seems to be running parameterised tests just fine,

screen shot 2018-03-21 at 22 59 47

**Comment by alf239** [comment]
Note also the following feature:

```
@ParameterizedTest
@MethodSource(names = "createWordsWithLength")
void withMethodSource(String word, int length) { }
 
private static Stream<Arguments> createWordsWithLength() {
    return Stream.of(
            ObjectArrayArguments.create("Hello", 5),
            ObjectArrayArguments.create("JUnit 5", 7));
}
```

We can use it to make out test inheritance cleaner, and get rid of the state.

**Comment by alf239** [comment]
Further reading: https://blog.codefx.org/libraries/junit-5-parameterized-tests/#Test-Name

**Comment by apete** [comment]
I'm all for using the available features of JUnit 5.

**Pull request merged**
