### PR TITLE
Rational approximation experiment

### PR DESCRIPTION
**Pull request by alf239**
It seems to work, mostly. We have 9 tests failing, most of them due to small discrepancies, and we do need to investigate those - but overall it's surprisingly robust for a half an hour job.

### CODE REVIEW

**Comment by alf239** [comment]
```

Failed tests: 
  BasicMatrixTest.testGetKyFanNormInt:365 Number != Number (real) expected:<(22394006679 / 551181874)> but was:<(40.62906952380944 + 0.0i)>
  BasicMatrixTest.testGetSingularValues:475 Number != Number expected:<8.459025654213246> but was:<8.459025654224055>
  BasicMatrixTest.testGetTraceNorm:512 Number != Number (real) expected:<(22394006679 / 551181874)> but was:<(40.62906952380944 + 0.0i)>
  BasicMatrixTest.testInvert:562 Access1D<?> != Access1D<?>, large norm differences 4.426303189664221E-12 !<< 1.0606601717773316
  BasicMatrixTest.testSolveBasicMatrix:851 Access1D<?> != Access1D<?>, large norm differences 6.0752397356632856E-12 !<< 1.7320508075659693
  BasicMatrixTest.testGetVectorNorm2:540->testGetVectorNormInt:1086 Number != Number (real) expected:<(415512399 / 293811635)> but was:<(1.4142135623730865 + 0.0i)>
  BasicMatrixTest.testNorm:794 double != double expected:<1.414213562373049> but was:<1.4142135623730865>

```

**Comment by alf239** [comment]
Most importantly of course, 0.1 is now 1/10 :)

**Comment by alf239** [comment]
The proper background is here: https://en.wikipedia.org/wiki/Continued_fraction

I would like to find a bettter stopping condition (remainder == 0.0 does seem inadequate in floating point arithmetics, we need something better I guess), as 1/10 clearly builds in two steps (0.0 + 1/10)

**Comment by alf239** [comment]
We need to calculate n such that (1 - epsilon)^n < epsilon, and use it as the array's size. Alternatively, we can forget about the array, and go with a recursive form; that's more readable, too, with no heap usage.

**Comment by alf239** [comment]
Weird, it seems my (arbitrary) limit of 40 steps has hit the sweet spot where we pass all the tests. Just stopping on the epsilon makes us make a couple more steps and fails the `BasicMatrixTest` above. 

Should be green now; @apete, what do you think?

**Comment by apete** [comment]
I just did a very quick JMH benchmark comparing the old and new valueOf methods. The old approach is roughly 1000 times faster.

**Comment by alf239** [comment]
Let's stay with the old approach for now then; we can offer rational approximation as a call, but the ugly fractions we're getting from the internal double representation work better and are easier to reason about.

BTW, was the test run for the array-backed option or for the recursive one?

**Comment by apete** [comment]
The array backed solution was the one I saw. Possibly I did some pull and didn't notice the change.

I would guess a recursive solution is faster.

Yes, keep the approximation method as a separate factory method.

**Comment by apete** [comment]
One problem with those BasicMatrix tests is that they primarily test for similar behaviour between different Scalar/Number implementations. If one implementation has significantly better characteristics  in some respect that could cause problems.

**Comment by apete** [comment]
Did another test where I definitely used the recursive version and the difference is 989x.

**Comment by alf239** [comment]
Returned the old good `valueOf`. Suspect we can improve the performance of `rational`,  but it's not clear whether we need to: on the rational/double boundary, the conversion should be negligible in comparison with the calculation itself; during the calculation, one would hope not to mix rationals and doubles.

Anyway, we should be green now, we've got a new method to play with, and can get back to it when it's clear whether we want a nice presentation over the speed and accuracy (for a certain definition of the latter).

**Pull request merged**
