### PR TITLE
ComplexNumber class

### PR DESCRIPTION
**Pull request by lostnut**
Hi, this is one of my first contributions/PR and I would like to contribute to OjAlgo.
This first PR/commit is the beginning of the refactor of the `ComplexNumber` class, I use in other projects. 
The main idea is to improve the public API of this class.

This commit includes javadoc comments for public API of the
ComplexNumber class.
Javadoc added for :
- Constants (public static final fields)
- Static factory methods
- Public constructors

Do not hesitate to correct it i'm still in learning process of open source contribution.

### CODE REVIEW

**Comment by lostnut** [comment]
The first time I used the `ComplexNumber` class, the constructor confused me. It just returns `ComplexNumber#ZERO` and brings nothing to the class API. Direct access to the available factory seems to be enough : 
- `ComplexNumber#valueOf(double)`
- `ComplexNumber#of(double, double)`
- `ComplexNumber#makePolar(double, double)`
- `ComplexNumber#valueOf(Number)`

What do you think of Deprecating/Removing the public constructor ?

**Comment by lostnut** [comment]
Thank you for your answer, I will revert previous commits and try to look at ComplexNumber tests.

**Comment by lostnut** [comment]
I have some questions about general ojAlgo design : 
1. Should we handle incoming exception for each method (at least when its obvious) ? 
For example, the `ComplexNumber` class defines a `compareTo` method without checking the specified argument. The method `ComplexNumber#compareTo(ComplexNumber reference)` throws NullPointerException if `reference` is null. Do you want to let NullPointerException pop off or should we handle it (throw a IllegalArgumentException) ? In `ComplexNumber` class all binary operations have the same behavior.

2. `equals()` methods use `Double.doubleToLongBits` for its implementation to handle NaN, POSITIVE_INFINITY, ...  The `Double.compare(double, double)` method handles it directly. Is it possible to replace it ?

3. `hashcode()` methods : for example in `ComplexNumber` class rely on a specific implementation which is exactly the same implementation available in java standard library : `Objects#hash(Object[])`. Is it possible to replace it ?

**Comment by apete** [comment]
1. Checking for null should only be done when it adds clarity to the code. Most of the time it should be obvious to the programmer if null is allowed or not. Generally speaking null methods arguments should never be required and rarely accepted, and methods should never return null. I don't see the point in replacing a NullPointerException with an IllegalArgumentException for the compareTo method.

2. Suppose you could. Most of the equals and hashCode methods are generated by the IDE (eclipse). Code changes should make things better. Doesn't need to be much, but how does calling `Double.compare(double, double)` instead make things better?

3. No that's not exactly the same. Calling `Objects#hash(Object[])` would box each of the `double` values in `Double` instances and then create an `Object[]` to store them in, right? That's a big difference to me.

(I'm currently on holiday with sporadic internet access.)

**Pull request merged**
