### PR TITLE
 a more correct implementation of LeftRightStore#limitOfRow

### PR DESCRIPTION
**Pull request by andrievskya**
it takes into account a special case, when the right part is zero (for the current row), so the length depends on the left part, which may have length less than mySplit

### CODE REVIEW

**Comment by apete** [comment]
Thanks for contributing. It looks correct, but why not also handle the case when the left part is zero? And the same improvements can be applied to the AboveBelowStore.

(Adding a test case never hurts.)

**Comment by andrievskya** [comment]
A fair point. 
By the way,  this solution turned out to be extremely ineffective for large block diagonal matrices, composed of many small ones, so I' m going to create another pull request with a better implementation.

**Comment by apete** [comment]
I believe that's why I decided on a simple solution (fast to deduce the firsts and limits) rather than a correct one.

Excessive use of the various LogicalStore implementations can be very inefficient.

**Comment by apete** [comment]
There is also the SuperimposedStore. Perhaps the blocks can be superimposed on a ZeroStore.

... or maybe what you need is an entirely new MatrixStore implementation. What are you trying to optimise= Memory consumption? Execution speed for some specific operation?

**Comment by andrievskya** [comment]
I'm trying to solve a mixed-integer optimization problem with a (sort of a) block diagonal matrix with up to  50-60K rows and columns, so I need some tools to handle such matrices in a reasonable time. 
By handling i mean construction from already existing blocks and transformation to compressed row storage.

From the memory point of view, with known size and structure of matrices, nothing but sparse matrices  comes to mind.

**Comment by apete** [comment]
Are you using the ojAlgo MIP solver for that? The problem sounds a bit large for ojAlgo.

Do you need to explicitly create the matrices?

**Comment by andrievskya** [comment]
I'm going to use a CBC solver, which have been proven to handle such sort of a problem (in matlab prototype), that's why i transform a matrix to a compressed row storage.

I create individual blocks in one place, and combine them into more complex structures, in another, and final block matrices may be different in different cases, so I need a commen mechanizm for this. 
In my tests, ojAlgo(with additions, for which i've just created another pull request) turned out to be quick enough for my purposes.

**Pull request closed without merging**
