### PR TITLE
Add public to abstract classes for better kotlin interop

### LINKED ISSUE #237: Make package-private and protected abstract classes and interfaces public to make Kotlin interop
**Is your feature request related to a problem? Please describe.**
I'm using Kotlin for my work to use ojAlgo alongside with Ktor framework.
When I try to multiply two matrices I get IllegalAccessError
```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class org.ojalgo.matrix.BasicMatrix from class ru.appmat.TestKt
	at ru.appmat.TestKt.main(test.kt:36)
	at ru.appmat.TestKt.main(test.kt)
```

This problem relates to a fundamental language-design issue https://youtrack.jetbrains.com/issue/KT-11700.
**Describe the solution you'd like**
Everything would work if you could **make** package-private and protected abstract classes and interfaces **public**.

### PR DESCRIPTION
**Pull request by goto1134**
Fixes #237

### CODE REVIEW

**Comment by goto1134** [comment]
All changed classes have a packageLocal modifier, have public inheritors, have at leas one public method that is not inherited from a superclass

**Comment by apete** [comment]
Is that the precise description of what's problematic? How did you find all the cases?

**Comment by apete** [comment]
In PlainArray all the public methods are declared somewhere else - some interface in org.ojalgo.structure I guess. Is this class problematic?

**Comment by goto1134** [comment]
You are right, there was a mistake in the algorythm. 
I used "Search Structurally" feature of IntelliJ IDEA with the following template:

```xml
<searchConfiguration name="packageLocal abstract class with public methods that have no supermethods" text="@Modifier(&quot;packageLocal&quot;) abstract class $Class$ {&#10;    &#10;    public $ReturnType$ $Method$ ($ParameterType$ $Parameter$);&#10;&#10;}" recursive="true" caseInsensitive="true" type="JAVA" pattern_context="default">
  <constraint name="__context__" within="" contains="" />
  <constraint name="Class" script="&quot;com.intellij.psi.search.searches.ClassInheritorsSearch.search(__context__).anyMatch({x -&gt; x.hasModifier(com.intellij.lang.jvm.JvmModifier.PUBLIC)})&quot;" within="" contains="" />
  <constraint name="ReturnType" within="" contains="" />
  <constraint name="Method" script="&quot;com.intellij.psi.search.searches.SuperMethodsSearch.search(__context__, __context__.getContainingClass(), true,false ).findFirst() == null&quot;" maxCount="2147483647" within="" contains="" />
  <constraint name="ParameterType" within="" contains="" />
  <constraint name="Parameter" minCount="0" maxCount="2147483647" within="" contains="" />
</searchConfiguration>
```
You can import it in your IDE to check the result.

That is not the generic description of the interop problem, but one of the cases where interop can fail. It can fail everywhere where you can run a method with one of the following characteristics:
1. public method of a protected/package-private abstract superclass
2. returns a generic extended from a protected/package-private abstract superclass
3. declares the return type of a protected/package-private abstract superclass

In these situations Kotlin can cast the instance of an abstract superclass subclass to superclass, but will not be allowed to by JVM because of visibility modifier.

**Comment by apete** [comment]
I'll merge this to a new branch `KotlinInteroperability`. The intention is for that branch to be merged to develop and then to master, and that there will be a v48.0.1 or v48.1.0 release with improved interoperability.

I'm not entirely happy about just making everything public - the classes were package private for a reason. I'll go through this case by case to see if there are alternatives.

For you: Build a snapshot version of this branch and keep track of (as I work on it) if it continuous to actually solve your problem. Expect a new version to be released sometime in January.

**Comment by goto1134** [comment]
Ok, thanks

**Pull request merged**
