### PR TITLE
Improved performance for the case with no presolver

### PR DESCRIPTION
**Pull request by fueralles**
The checkup of expressions and fixed variables is very slow for some problems. In the case of no presolver selected it is not needed. I could improve the performance even on small problems, e.g. the runtime is reduced from ~4 min to 2 s.

### CODE REVIEW

**Comment by apete** [comment]
Thanks for the PR, but it looks like you've changed the entire file. I won't merge a PR like that.

What did you change? To turn off the presolvers all you need to do is `ExpressionsBasedModel.clearPresolvers()` or `ExpressionsBasedModel.removePresolver(...)` if you know which one is causing the problem.

Can you give me some background on your problem: Are you using the ojAlgo solvers or some external/native solver? What size problem? Essentially there are only 2 presolvers in ojAlgo (that are enabled by default). It's quite easy to turn then on/off individually. Can you do that and tell me which one is causing the problem?

I feel this should be an issue rather than a PR at this point. When we know more about the problem maybe it will result in a PR.

**Comment by fueralles** [comment]
I don't know why the whole file was changed. Maybe the file format or some spaces were changed by my program. Locally the comparison works. I only changed line 888 and 918-920 in my file. 

I know that I can switch off the presolver with `ExpressionsBasedModel.clearPresolvers()` but the performance lost happens in the data preparation beforehand. I use an external solver. The problem, I mentioned as an example, has around 20,000 variables and roughly 30,000 expressions (lot's of them result by the introduction of slack variables so that the lower and upper bound could not defined in the variable creation process). The main bottleneck seems to be `myExpressions.values().stream().anyMatch(e -> e.includes(tmpVariable));` in line 1089 in your file. 

In my opinion it was more a question of design if the data preparation is considered in the case of no presolver existing or not. Thus, I did the PR (and I wanted to contribute something instead of always opening some issues).

**Comment by apete** [comment]
I appreciate your willingness to contribute!

Something seems wrong regarding identifyFixedVariables() - what it does and how often it's called.

**Comment by apete** [comment]
I don't understand what you said about expressions and slack variables. You should not model things like slack variables - they're created for you, if needed, when instantiating the solver.

**Comment by fueralles** [comment]
In the first run I compute the problem without them. If it fails, I will add some specific "slack" variables:
See the following example for the expressions:
`0 <= a <=1` 
is changed to 
`a`, `0<s`, `0-s <=a`, `a<=1+s`
or changes like that
`a`, `0<s1<0.5`, `0<s2`,`0-s1-s2 <=a`, `a<=1+s1+s2`.

What would be the usual way to do this?

However, the performance boost for my problem even exist for the problem without slack variables.

**Comment by apete** [comment]
The first example looks like your simply relaxing the constraint, but I don’t know what you want/need.


I’m looking at alternatives to calling

 identifyFixedVariables()

as often as is the case now.

As you pointed out it’s probably too slow, not always useful and called too often. But I can’t or wont remove that functionality completely. It’s needed in some cases.

/Anders

**Comment by fueralles** [comment]
Correct, I am relaxing the constraints but by introducing slack variables I have a measurement for the violation. The measurement is what I need for my analysis. 

You have a much better overview how it is used. For my purposes it seems to be worth to skip the data checkup functions.

**Comment by apete** [comment]
I’ve refactored a bit.

For now, at least, that piece of code is only called once. It used to be called once for each presolver iteration.

In the future I’ll try to make this configurable/optional just like (the other) presolvers.

A trick/hack that should prevent this code from being executed is to not define the “weights” directly on the variables, but instead use a separate objective function expressions. (This contradicts the the usual recommendation, and is not guaranteed to work in the future.)

Check out the code from the optexp branch to test the changes I’ve made.

/Anders

**Comment by apete** [comment]
Now, if you call `ExpressionsBasedModel.clearPresolvers()` then even that "data checkup function" is skipped. This should be enough.

**Pull request closed without merging**
